### ISSUE TITLE
md里面没法直接使用网络图片吗？请指导，感谢

### ISSUE THREAD

**Issue by jamestore** [izmttk/astro-mecure#6]
md里面没法直接使用网络图片吗？请指导，感谢，
插入网络图片但显示不出来。

![]()的方式。

**Comment by izmttk** [comment]
能描述一下具体情况吗，比如md内容和最终结果

**Comment by jamestore** [comment]
![image](https://github.com/user-attachments/assets/e48654e3-4949-43c2-9ee2-b3fb957b1a8d)
类似这个写法在astro的https://github.com/saicaca/fuwari/tree/main中是可以正常显示图片的。但在你的模板下面图片不支持，加载不出来，或报错。

**Comment by izmttk** [comment]
该问题已在最新提交 4889607bbb98ee0431525b2302f4c70f70aa82e7 中修复，请看一下是否还存在问题

**Comment by jamestore** [comment]
> 该问题已在最新提交 [4889607](https://github.com/izmttk/astro-mecure/commit/4889607bbb98ee0431525b2302f4c70f70aa82e7) 中修复，请看一下是否还存在问题

已测试，完美。。感谢！
