### ISSUE TITLE
md使用网络图片有的存在问题，请原谅我的测试不全面。感谢

### ISSUE THREAD

**Issue by jamestore** [izmttk/astro-mecure#7]
md使用网络图片有的存在问题，请原谅我的测试不全面。感谢
刚才把项目全部迁移过去的时候，发现有些图片显示不出来。有些可以。
代码如下：
![image](https://github.com/user-attachments/assets/cc317f63-7678-4a57-a8ee-141bccae1863)

效果如下：
![image](https://github.com/user-attachments/assets/1a98f4dc-72be-444b-a9cb-9c9f05f87b0b)

**Comment by jamestore** [comment]
可以修复吗？大佬。我迁移卡在这里了，在线等待哈，非常感谢！

**Comment by izmttk** [comment]
这是我引入的一个新md语法，用两个`!!`包裹文本会产生黑幕效果，你的链接里有文本触发了这个语法，可以试试把url里的叹号转义`\!`
不过黑幕语法优先于md已有语法确实是个问题，我会尝试修复

**Comment by jamestore** [comment]
![image](https://github.com/user-attachments/assets/b21da547-bfe5-4612-af76-baa8fd2e5d06)

这里需要转义是吗？我先等些天，要是能修复就最好。主要是太多旧内容了，批量处理不知道会不会有影响。

**Comment by jamestore** [comment]
_\!\!2

确实可以这样子，但好象不好批量操作。

**Comment by jamestore** [comment]
![image](https://github.com/user-attachments/assets/75a3ae21-56f3-4f2b-a0de-0dfdddb825ae)

**Comment by jamestore** [comment]
大佬，还是要依靠你了。图床生成的图片命名都是这样子，我好象不知道怎么正则过滤并批量替换掉。

**Comment by izmttk** [comment]
我会尽快修复

**Comment by jamestore** [comment]
评估了吗？预计什么时候可以呢？能修复吗。。不好意思哈，不应该催你，只是我真的很喜欢你这个模板，想整站迁移过去。

**Comment by izmttk** [comment]
看来这个问题需要是时间比我想象的多，如果你不需要这些新语法，你可以在 [astro.config.ts](https://github.com/izmttk/astro-mecure/blob/main/astro.config.ts) 中手动禁用，只需要注释以下几行：

https://github.com/izmttk/astro-mecure/blob/4889607bbb98ee0431525b2302f4c70f70aa82e7/astro.config.ts#L45
https://github.com/izmttk/astro-mecure/blob/4889607bbb98ee0431525b2302f4c70f70aa82e7/astro.config.ts#L79

**Comment by jamestore** [comment]
感谢。这样已经可以满足我的需求了。
