### ISSUE TITLE
朋友，有没有交流的群之类的。没办法，只能用开issues的方式提问，请原谅。。几个问题，请教下。感谢

### ISSUE THREAD

**Issue by jamestore** [izmttk/astro-mecure#8]
1。百度/google统计怎么添加呢。好象加到html.asto的header中，有报错，没添加成功。

<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?d4114808756bc160fc61d59cce79d7db";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>

2。logo和左上角的svg文件，怎么修改呢？有办法直接文字生成svg吗？应该是有好用的工具吗？ 另外尺寸多少合适的，我尝试了一些，要么大了，要么小了，总是不够美观。

**Comment by izmttk** [comment]
hello
关于第 1 个问题，咱们需要更多信息才能解决，不如提供一些报错信息看看
关于第 2 个问题，刚刚的 commit 添加了一个 `navbar.logo` 配置项，同时发生变化的还有 `hero.title`，`hero.logo` 的功能并合并到 `hero.title` 中，该配置项已经被删除了。
具体来说，这两个配置项 `navbar.logo` `hero.title` 都支持直接字符串和Astro组件，字符串就不用多说了，Astro组件会给你最大可能的客制化能力，举个例子：
如果你想把图片放在这两项的位置上，需要创建一个Astro文件，推荐放在 `src/custom` 文件夹中，假设现在有一个文件 `src/custom/Logo.astro` ：
```astro
随便什么html内容，如果你不懂 astro 的模板语法， 直接当作 html 文件写好了
比如图片：
<img src="xxx" alt="xxx" class="xxx" />
或者文字：
<span class="xxx">This is my site.</span>
你可以用任何方法修改样式，直接写 style 属性，或是 class+style 标签，或者站点支持 tailwindcss，如果你用过。
```
在 `config.ts` 里，你需要这么配置
```ts
import Logo from '@/custom/NavLogo.astro';
const config = {
  navbar: {
    logo: Logo,
    // 同时支持动态导入语法，我个人更喜欢于动态导入的写法
    // logo: import('@/custom/NavLogo.astro'),
  }
}
```

**Comment by izmttk** [comment]
相关 commit 7a01c237c937280ccf8a0282f840b97388491625 0db567b6df3567ea7d839242f9e2d4393362851c

**Comment by jamestore** [comment]
感谢

**Comment by jamestore** [comment]
![image](https://github.com/user-attachments/assets/bcae2bd7-3063-4972-8d36-1000ca509920)

不是很懂技术，不好意思。

**Comment by jamestore** [comment]
'_hmt' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)


Property 'dataLayer' does not exist on type 'Window & typeof globalThis'.ts(2339)


大概是没定义或引用方式有问题，技术比较菜。这代码是百度或google统计直接提供的，只是我可能引用方式有问题导致，但不知道该写在哪里或更好。

**Comment by jamestore** [comment]
> 相关 commit [7a01c23](https://github.com/izmttk/astro-mecure/commit/7a01c237c937280ccf8a0282f840b97388491625) [0db567b](https://github.com/izmttk/astro-mecure/commit/0db567b6df3567ea7d839242f9e2d4393362851c)

![image](https://github.com/user-attachments/assets/a0f82a9b-79ac-43f1-8a9b-37766f6b7d1e)

![image](https://github.com/user-attachments/assets/21e0cc88-5527-40eb-b9e3-f63fd84c247d)

更新后好象影响到文章的图片了。

**Comment by izmttk** [comment]
> '_hmt' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)

这个是typescript的类型检查，这段代码没有严格按照ts的类型规则写，所以给了警告，但是网站应当是可以正常执行的，如果你不想在IDE中看到这些报错，可以在js代码开头加上 `// @ts-nocheck` 以禁用本文件的ts检查



> > 相关 commit [7a01c23](https://github.com/izmttk/astro-mecure/commit/7a01c237c937280ccf8a0282f840b97388491625) [0db567b](https://github.com/izmttk/astro-mecure/commit/0db567b6df3567ea7d839242f9e2d4393362851c)
> 
> ![image](https://private-user-images.githubusercontent.com/180855527/371009529-a0f82a9b-79ac-43f1-8a9b-37766f6b7d1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NDQ4MjksIm5iZiI6MTcyNzQ0NDUyOSwicGF0aCI6Ii8xODA4NTU1MjcvMzcxMDA5NTI5LWEwZjgyYTliLTc5YWMtNDNmMS04YTliLTM3NzY2ZjZiN2QxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QxMzQyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmFhN2JhNWZhYzllMWI5ZjQ4ZWZkNjIwYzcwNGZhYzAzOTRiMjBmMGM5Y2NlNzI3NzQyNTA5NmRjZWQ1YjgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jggeQhEp6UvDWonRNgpGIzDXFZNpGWHm6ngtGa1Phj0)
> 
> ![image](https://private-user-images.githubusercontent.com/180855527/371009848-21e0cc88-5527-40eb-b9e3-f63fd84c247d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NDQ4MjksIm5iZiI6MTcyNzQ0NDUyOSwicGF0aCI6Ii8xODA4NTU1MjcvMzcxMDA5ODQ4LTIxZTBjYzg4LTU1MjctNDBlYi1iOWUzLWY2M2ZkODRjMjQ3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QxMzQyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODUwM2VlZGY2OGE5ZWEwN2VjMzdlNjIxNzYzMjk1ZDY3ZjE1MWZjYmI2YTk2ZDAwNDc4OGU0ZmRjYmRjMWNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bothfkXlqJA4yX8aISJWeLKsINz5j3cu0MJDNOZdjFE)
> 
> 更新后好象影响到文章的图片了。

这个我这里测试没问题呀，请再确认一下，如果确实有问题请提供一下代码好了
